### PR TITLE
Kaufhaus implementation

### PR DESCRIPTION
**Pull request by kaspar-naaber**
(Issue: #81)
- [x] Add shopping cart button styles.
- [x] Bind with Design Editor.

### CODE REVIEW

**Comment by SSirjes** [comment]
* [ ] If shopping cart button stays under header, then 'My order' modal will not open.
Video: http://recordit.co/cqgHHp040j

**Comment by SSirjes** [comment]
* [ ] On smaller screen shopping cart button stays under site name and language menu
Happens: Mac, Google Chrome
Video: http://recordit.co/qNPSyDm7gN

**Comment by kaspar-naaber** [comment]
#83 needs to be done before I can continue implementing.

**Comment by kaspar-naaber** [comment]
- [ ] Banner type checkout button covers topbar.
- [ ] Banner type checkout button covers mobile menu button.
- [ ] Banner type checkout button covers mobile search button.

**Pull request closed without merging**
